# architecture
if(WIN32)
    EXECUTE_PROCESS(COMMAND wmic os get osarchitecture OUTPUT_VARIABLE ARCHITECTURE_CMD_RAW)
    string(REPLACE "\r" "" ARCHITECTURE_CMD_CLEANR ${ARCHITECTURE_CMD_RAW})
    string(REPLACE " " "" ARCHITECTURE_CMD_NOSPACE ${ARCHITECTURE_CMD_CLEANR})
    string(REPLACE "\n" "_" ARCHITECTURE_CMD_NON ${ARCHITECTURE_CMD_NOSPACE})
    string(REPLACE "__" ";" ARCHITECTURE_LIST_1 ${ARCHITECTURE_CMD_NON})
    string(REPLACE "_" ";" ARCHITECTURE_LIST ${ARCHITECTURE_LIST_1})
    list(GET ARCHITECTURE_LIST 1 ARCHITECTURE)
else()
    EXECUTE_PROCESS( COMMAND uname -m COMMAND tr -d '\n' OUTPUT_VARIABLE ARCHITECTURE )
endif()

# get current git commit hash
execute_process(
        COMMAND git log -1 --format=%h
        WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
        OUTPUT_VARIABLE GIT_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
)